---
title: "Approximations"
author: "Thomas Sandmann"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    theme: united
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Notes and code snippets for chapter 2

```{r}
library(rethinking)
library(parallel)
options(mc.cores = parallel::detectCores() - 1L)
```

## 2.3

```{r}
par(mfrow = c(2, 1))
n_points <- 20
# define grid
p_grid <- seq(0, 1, length.out = n_points)

# define prior
prior <- rep(1, n_points)  # uniform
prior <- ifelse(p_grid < 0.5, 0, 1)  # step
prior <- exp(-5*abs(p_grid - 0.5))  # peaked

par(mar = c(4, 4, 4, 1))
plot(p_grid, prior, type = "b",
     ylab = "prior probability",
     xlab = "parameter grid",
     pch = 19, 
     cex = 0.5
     )
mtext("Prior probability")

# compute likelihood at each value
likelihood <- dbinom(6, size = 9, prob = p_grid)

# compute product of likelihood and prior
unstd.posterior <- likelihood * prior

# standardize so it sums to 1
posterior <- unstd.posterior / sum(unstd.posterior)
par(mar = c(4, 4, 3, 1))
plot(p_grid, posterior, type = "b",
     xlab = "probability of water", 
     ylab = "posterior probability",
     pch = 19, 
     cex = 0.5)
mtext("20 points")
par(mfrow = c(1, 1), 
    mar = c(5.1, 4.1, 4.1, 2.1))
title("Grid approximation")
```

## 2.6 Quadratic approximation

```{r}
globe.qa <- rethinking::quap(
  alist(
    W ~ dbinom(W + L, p),  # binomial likelihood
    p ~ dunif(0, 1)  # uniform prior
  ),
  data = list(W = 6, L = 3)
)
rethinking::precis(globe.qa)
```

```{r}
# analytical solution
W <- 6
L <- 3
curve(dbeta(x, W + 1, L + 1), from = 0, to = 1, col = "blue",
      xlab = "Proportion water", ylab = "Density")
# quadratic approximation
curve(dnorm(x, 0.67, 0.16), add = TRUE)
mtext(sprintf("n = %s", W + L))
```